
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Nov 15 11:04:45 PET 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 36;
  public static final int In = 13;
  public static final int Class = 3;
  public static final int Coma = 45;
  public static final int End = 6;
  public static final int Until = 11;
  public static final int Llave_c = 42;
  public static final int Llave_a = 41;
  public static final int Def = 2;
  public static final int VariableGlobal = 53;
  public static final int If = 7;
  public static final int RangoInclusivo = 27;
  public static final int Comparacion = 25;
  public static final int IgualIgual = 23;
  public static final int Redo = 18;
  public static final int Diferente = 24;
  public static final int Rescue = 19;
  public static final int TripleIgual = 26;
  public static final int RangoExclusivo = 28;
  public static final int Else = 9;
  public static final int Break = 16;
  public static final int Corchete_c = 44;
  public static final int Corchete_a = 43;
  public static final int Punto = 46;
  public static final int Return = 14;
  public static final int While = 10;
  public static final int Division = 33;
  public static final int Parentesis_c = 40;
  public static final int Modulo = 34;
  public static final int Parentesis_a = 39;
  public static final int For = 12;
  public static final int P_coma = 48;
  public static final int EOF = 0;
  public static final int DosPuntos = 47;
  public static final int Simbolo = 54;
  public static final int Not = 37;
  public static final int And = 35;
  public static final int error = 1;
  public static final int FlechaHash = 38;
  public static final int When = 22;
  public static final int Module = 4;
  public static final int ERROR = 55;
  public static final int Do = 5;
  public static final int VariableClase = 52;
  public static final int Case = 21;
  public static final int Exponenciacion = 29;
  public static final int Yield = 15;
  public static final int Identificador = 49;
  public static final int Elsif = 8;
  public static final int Resta = 31;
  public static final int Ensure = 20;
  public static final int Multiplicacion = 32;
  public static final int Numero = 50;
  public static final int Suma = 30;
  public static final int Next = 17;
  public static final int VariableInstancia = 51;
}

